name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "build $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "check $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "foo $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
