name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "# Sumamry from build" >> $GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "4 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "5 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "6 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "# Sumamry from check" >> $GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "4 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "5 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "6 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "# Sumamry from foo" >> $GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "4 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "5 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "6 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
