name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "# Summary from ubuntu" >> $GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY

  windows:
    needs: [macos]
    runs-on: windows
    steps:
      - run: echo "# Summary from windows" >> $env:GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $env:GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $env:GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $env:GITHUB_STEP_SUMMARY

  macos:
    runs-on: macos-latest
    needs: [ubuntu]
    steps:
      - run: echo "# Summary from macos" >> $GITHUB_STEP_SUMMARY    
      - run: echo "1 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "2 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY
      - run: echo "3 $GITHUB_STEP_SUMMARY" >> $GITHUB_STEP_SUMMARY

